name: Build & Push to Cloudraya

on:
  push:
    branches:
      - main
      - release/*

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 🛠️ Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: 🔖 Read version from VERSION file
        id: version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      # - name: ⚙️ Install swag and generate Swagger docs
      #   run: |
      #     go install github.com/swaggo/swag/cmd/swag@latest
      #     export PATH=$PATH:$(go env GOPATH)/bin
      #     swag init

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔐 Log in to Cloudraya registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: 🚀 Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ vars.REGISTRY_URL }}/${{ vars.REGISTRY_NAMESPACE }}/learngolang-api:${{ github.ref_name }}
            ${{ vars.REGISTRY_URL }}/${{ vars.REGISTRY_NAMESPACE }}/learngolang-api:latest
